/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 18-Feb-2021 16:30:01
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 100
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include <stdint.h>
/* 
 * Expected path to tmwtypes.h 
 * D:\Matlab\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
#define BPL = 100;
int16_t BP[100] = {
       -5,     -6,    -10,    -12,    -10,      1,     18,     38,     55,
       60,     50,     25,     -7,    -36,    -48,    -40,    -14,     11,
       16,    -17,    -90,   -187,   -271,   -300,   -243,    -97,    105,
      305,    435,    449,    345,    176,     29,     -6,    119,    376,
      659,    807,    666,    155,   -679,  -1653,  -2482,  -2868,  -2596,
    -1625,   -120,   1580,   3047,   3894,   3894,   3047,   1580,   -120,
    -1625,  -2596,  -2868,  -2482,  -1653,   -679,    155,    666,    807,
      659,    376,    119,     -6,     29,    176,    345,    449,    435,
      305,    105,    -97,   -243,   -300,   -271,   -187,    -90,    -17,
       16,     11,    -14,    -40,    -48,    -36,     -7,     25,     50,
       60,     55,     38,     18,      1,    -10,    -12,    -10,     -6,
       -5
};
