// lowpass.h is the header file for the low pass filter on the Teensy
/* The FIR_Teensy.ino file will be the same, as it is an implementation
of a FIR filter that takes in the coefficients from this file. In Lab 3,
the coefficients kernel was generated by a Matlab designer. In our project,
we will be reading in from the terminal/console and using those coefficients 
as the coefficients kernel. */

#include <stdint.h>
#define LPL 100
char * getline(void) {
    char * line = malloc(100), * linep = line;
    size_t lenmax = 100, len = lenmax;
    int c;

    if(line == NULL)
        return NULL;

    for(;;) {
        c = fgetc(stdin);
        if(c == EOF)
            break;

        if(--len == 0) {
            len = lenmax;
            char * linen = realloc(linep, lenmax *= 2);

            if(linen == NULL) {
                free(linep);
                return NULL;
            }
            line = linen + (line - linep);
            linep = linen;
        }

        if((*line++ = c) == '\n')
            break;
    }
    *line = '\0';
    return linep;
}

int16_t LP[100] = {
        4,     -1,     -2,     -4,     -7,    -11,    -15,    -19,    -22,
      -24,    -24,    -21,    -14,     -4,     10,     27,     47,     68,
       88,    105,    117,    122,    116,     98,     67,     22,    -35,
     -101,   -174,   -248,   -317,   -373,   -411,   -421,   -399,   -337,
     -232,    -84,    109,    341,    608,    900,   1207,   1516,   1815,
     2089,   2326,   2515,   2646,   2714,   2714,   2646,   2515,   2326,
     2089,   1815,   1516,   1207,    900,    608,    341,    109,    -84,
     -232,   -337,   -399,   -421,   -411,   -373,   -317,   -248,   -174,
     -101,    -35,     22,     67,     98,    116,    122,    117,    105,
       88,     68,     47,     27,     10,     -4,    -14,    -21,    -24,
      -24,    -22,    -19,    -15,    -11,     -7,     -4,     -2,     -1,
        4
};
